- hosts: Company_1 
  gather_facts: false
  connection: network_cli
  vars_prompt:

    - name: show_command
      prompt: What is your "show" command?
      private: no

  tasks:
  - name: Run command
    ios_command:
     commands:
       - "{{ show_command }}" 
    register: showcommand

  - debug: var=showcommand.stdout_lines