- hosts: SW1
  gather_facts: false
  connection: network_cli
  vars_files:
    - ./vars/ios_check_vars.yaml

  tasks:
  - name: Show running config
    ios_command:
     commands:
       - show running-config
    register: showrun

  - name: check config
    debug:
      msg: "{{ item }} - OK"
    when: 'item in showrun.stdout[0]'
    with_items: "{{ config }}"

  - name: check config is missing
    debug:
      msg: "{{ item }} - MISSING!!!"
    when: 'item not in showrun.stdout[0]'
    with_items: "{{ config }}"