- hosts: Company_1
  gather_facts: false
  connection: network_cli
#  serial: 1


  tasks:
    - name: Show running config
      ios_command:
       commands:
         - show ip route
      register: showroute
  
  
    - name: get local routes
      set_fact: get_local_routes="{{showroute.stdout[0] | regex_findall('^L.*', multiline=True) }}"
  
    - name: print 
      debug:
        msg: "{{ get_local_routes }}"

    - name: check hosts table directory
      file:
        path: "./tables/{{ inventory_hostname }}"
        state: directory

    - name: create file 
      copy:
        content: "{{ get_local_routes | to_nice_yaml }}"
        dest: "./tables/{{ inventory_hostname }}/{{ inventory_hostname }}_local_routes"

