- hosts: Lab
  gather_facts: false
  connection: local
  vars:
    git: /etc/ansible/ansible_v2
  
  tasks:

    - name: check the directory status
      command: git status
      args:
        chdir: "{{ git }}"
      register: gitchanges
      changed_when: false
      delegate_to: localhost
      run_once: yes

    - debug: var=gitchanges.stdout_lines

    - name: get git commits
      set_fact: get_git_commits="{{ gitchanges.stdout | regex_findall('^.*(tables/../.*routing_table).*', multiline=True) }}"


    - debug: var=get_git_commits