- hosts: Company_1 
  gather_facts: false
  connection: network_cli
  vars_files:
    - ./vars/ios_vars.yaml

  tasks:
  - name: Show running config
    ios_command:
     commands:
       - show running-config
    register: showrun

#  - debug: var=showrun.stdout_lines

  - name: get ntp servers
    set_fact: get_ntp_servers="{{showrun.stdout[0] | regex_findall('^ntp server [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}', multiline=True) }}"

  - name: get dns servers
    set_fact: get_dns_servers="{{showrun.stdout[0] | regex_findall('^ip name-server [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}', multiline=True) }}"

  - name: add ntp server
    ios_config:
      lines:
        - "{{ item }}"
    when: 'item not in get_ntp_servers'
    with_items: "{{ ntp_servers }}"

  - name: add dns server
    ios_config:
      lines:
        - "{{ item }}"
    when: 'item not in get_dns_servers'
    with_items: "{{ dns_servers }}"

  - name: delete useless ntp server
    ios_config:
      lines:
        - "no {{ item }}"
    when: 'item not in ntp_servers'
    with_items: "{{ get_ntp_servers }}"

  - name: delete useless dns server
    ios_config:
      lines:
        - "no {{ item }}"
    when: 'item not in dns_servers'
    with_items: "{{ get_dns_servers }}"

#  - name: save running-config
#    ios_config:
#      save_when: modified

#  - debug: var=get_ntp_servers
#  - debug: var=get_dns_servers